### ISSUE TITLE
Bagnon 8.2.29 messed with the garbage plugin

### ISSUE THREAD

**Issue by Nillx** [AzeriteTeam/Bagnon_ItemInfo#6] opened 2020-01-12 13:01 UTC
> 8.2.29
> Now, if no plugins like Bagnon Scrap are installed, marks sellable gray items with the default junk coin icon.

At first the garbage plugin seems to be working fine but if i hover over a grey item it starts showing a gold icon in th e top left corner. If i close my bag and open it again its not showing unless i hover over it again.

**Comment by LudiusMaximus** [comment] 2020-01-13 13:39
The Bagnon [changelog of 8.2.29 ](https://www.curseforge.com/wow/addons/bagnon/files/2858642) says: Now, if no plugins like Bagnon Scrap are installed, marks sellable gray items with the default junk coin icon.

I guess this is the problem here.

**Comment by goldpaw** [comment] 2020-01-13 14:01
This garbage part of this plugin tones down and desaturates garbage items. That is working as intended. Bagnon now follows the default UI behavior in regards to the junk icon, meaning it's visible while at a vendor, hidden otherwise. That was the same behavior the garbage part of this plugin had. That too, is working as intended. 

If you're using bagnon scrap in addition to this, any bugs are a result of that. Bagnon Scrap highlights junk items, this one tones them down. Obviously they can't be used together. 

No bugs on my end. Closing this.

**Comment by LudiusMaximus** [comment] 2020-01-13 14:20
Sorry, but I beg to differ.
Just tried it with only Bagnon and Bagnon ItemInfo activated and it is still like the OP describes it.

If Bagnon is run on its own, the coin is **always** shown for scrap items, not just while at vendors. This is apparently the way Bagnon is intending it to be now.

If you activate Bagnon ItemInfo on top. The coins only become visible after once hovering over the item.

**Comment by Nillx** [comment] 2020-01-13 14:24
made a quick video example: https://www.youtube.com/watch?v=aY_j65gL8Ws

**Comment by goldpaw** [comment] 2020-01-13 17:46
Ok, I see the problem here. I didn't realise there had been a bagnon update two days ago, I was testing with the version from December 26th. The latest update to bagnon was ofc ONLY to this! 

So no wonder everything was working as intended on my end... I used the old version my plugins were written for, lol! SORRY! :D

**Comment by goldpaw** [comment] 2020-01-13 17:47
And yeah, totally my bad here. The bagnon version was written in the issue title, even. Should have been obvious to me.

**Comment by goldpaw** [comment] 2020-01-13 17:57
Fixed in 1.0.13-Release, should be available on Twitch and CurseForge soon!

**Closed by goldpaw** 2020-01-13 17:57 UTC
Labels: bug
